name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        node: [12, 14, 16]
        yarn-args: ["--frozen-lockfile"]
        include:
          - node: 17
            yarn-args: --no-lockfile
    name: 'Tests - Node ${{ matrix.node }}'
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: yarn
    - name: Install Dependencies
      run: yarn install
    - name: Lint JS
      run: yarn lint
    - name: Run Test
      run: yarn test
